### ISSUE TITLE
Please change the spelling of "Mundo" to "World" ?   

### ISSUE THREAD

**Issue by philiprbrenan** [Maria-lim04/maria-lim04.github.io#1]
Please could you change the spelling at the start of the web page from "Hello Wordl" to "Hello World" ?  Or if  you prefer perhaps "Hola Mundo" ?

**Comment by Maria-lim04** [comment]
I did
you can see please ...🤓

**Comment by philiprbrenan** [comment]
I can see!  It is absolutely perfect.  Please push "close" under this box to show that this issue has been fixed and no further action is required?
